### ISSUE TITLE
A warning now exists

### ISSUE THREAD

**Issue by XxsuperdeadlysniperxX** [Gdeft/portal#9]
A warning that jar files are inherently unsafe exists and your mod is a jar file

**Comment by MEEPofFaith** [comment]
If you're trying to download it just press the "keep" button to confirm that you want it.

**Comment by Goobrr** [comment]
~~i thought this mod died~~

**Comment by XxsuperdeadlysniperxX** [comment]
> If you're trying to download it just press the "keep" button to confirm that you want it.

Im on android btw

**Comment by BlueWolf3682** [comment]
suffer, i guess

**Comment by Gdeft** [comment]
It is a jar mod, the prompt was just warning you on how jar-mods are capable of accessing the stuff that are blacklisted in JavaScript-based modding. Fortunately, I have no intentions of creating a malicious software or some kind.

However, I don't really want to continue this mod anymore as I am already busy with other stuff. I recommend installing [sk7725/BetaMindy](https://github.com/sk7725/BetaMindy) if you want to play a good mod that is made in Java. I will be removing the topics so that the mod browser won't be detecting this mod.
